import type { NextPage } from "next";
import { MongoClient } from "mongodb";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import MainPage from "@components/MainPage";

export interface goodsPropsTypes {
  goods: {
    brand: string;
    id: string;
    name: string;
    price: number;
    image: string;
    type: string;
  }[];
}

const Home: NextPage<goodsPropsTypes> = ({goods}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage goods={goods} />
    </div>
  );
};

export async function getStaticProps() {
  const client = await MongoClient.connect(
    "mongodb+srv://feeduraddiction:Vjq1Gfhjkm2qwerty@cluster0.8swm7.mongodb.net/yourtime-cosmetics?retryWrites=true&w=majority"
  );
  const db = client.db();

  const goodsCollection = db.collection("yourtime");

  const goods = await goodsCollection.find().toArray();

  client.close();

  return {
    props: {
      goods: goods.map((good) => {
        return {
          brand: good.brand,
          name: good.name,
          id: good._id.toString(),
          image: good.image,
          price: good.price,
          type: good.type,
        };
      }),
    },
  };
}

export default Home;
